inherit_gem:
  makandra-rubocop:
    - config/default.yml
    - config/ext/rails.yml
    - config/ext/rspec.yml
    - config/ext/rspec_rails.yml
    - config/ext/capybara.yml
    - config/ext/factory_bot.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  SuggestExtensions: false

# Experimenting with a different gem project structure.
Gemspec/DevelopmentDependencies:
  Enabled: false

# This is a CLI tool.
# If we ever allow programmatic non-CLI usage of this gem,
# we need to move all `exit(1)` calls to the CLI layer.
Rails/Exit:
  Enabled: false

# The main file under `lib/` should have the same name as the `.gemspec`
Naming/FileName:
  Exclude:
    - Rakefile.rb
    - '**/lib/*.rb'
