inherit_gem:
  makandra-rubocop:
    - config/default.yml
    - config/ext/rails.yml
    - config/ext/rspec.yml
    - config/ext/rspec_rails.yml
    - config/ext/capybara.yml
    - config/ext/factory_bot.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  Enabled: false
