name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/rubocop.gemfile
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: rubocop
      run: |
        bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      CI: true

    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: "3.4"
          gemfile: "gemfiles/railsmain.gemfile"
        - ruby: "3.3"
          gemfile: "gemfiles/rails72.gemfile"
        - ruby: "3.2"
          gemfile: "gemfiles/rails71.gemfile"
        - ruby: "3.1"
          gemfile: "gemfiles/rails70.gemfile"
        - ruby: "2.7"
          gemfile: "gemfiles/rails6.gemfile"

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: |
        bundle exec rspec
